name: arctium
description: Reliable UI-oriented service locator with great performance, Widget lifecycle bindings, queued auto disposal and useful UI integrations.
version: 0.0.1
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/LooksGoodApp/flutter-arctium-dependency-injection

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.5